[package]
name = "github-grid"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
git2 = "0.20.2"
indicatif = "0.18.0"
rand = "0.9.2"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.3"
